---
# tasks file for docker_deploy
- name: Create dirs for Gitlab volumes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs
  become: true

- name: Start a container
  docker_container:
    name: "{{ container_name }}"
    hostname: "{{ container_name }}"
    image: 'gitlab/gitlab-ce:latest'
    ports: 
      - "80:80"
      - "443:443"
      - "2222:22"
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://{{ ansible_ssh_host }}"
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
  become: true
