version: '3.3'
services:
  post_db:
    image: mongo:${POST_DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      monitoring_net:

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${PORT_UI}:9292/tcp
    networks:
      - front_net
      - monitoring_net

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      back_net:
      front_net:
        aliases:
          - post_host
      monitoring_net:

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
      front_net:
        aliases:
          - comment_host
      monitoring_net:

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
    - '9090:9090'
    volumes:
    - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - monitoring_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - monitoring_net

volumes:
  post_db:
  prometheus_data:

networks:
 monitoring_net:
   driver: bridge
   driver_opts:
     com.docker.monwork.enable_ipv6: 'false'
   ipam:
     driver: default
     config:
      - subnet: 10.0.0.0/24

 front_net:
   driver: bridge
   driver_opts:
     com.docker.monwork.enable_ipv6: 'false'
   ipam:
     driver: default
     config:
      - subnet: 10.0.1.0/24

 back_net:
   driver: bridge
   driver_opts:
     com.docker.monwork.enable_ipv6: 'false'
   ipam:
     driver: default
     config:
      - subnet: 10.0.2.0/24
