version: '3.3'
services:
  post_db:
    image: mongo:${POST_DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT_UI}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
 front_net:
   driver: bridge
   driver_opts:
     com.docker.monwork.enable_ipv6: 'false'
   ipam:
     driver: default
     config:
      - subnet: 10.0.1.0/24

 back_net:
   driver: bridge
   driver_opts:
     com.docker.monwork.enable_ipv6: 'false'
   ipam:
     driver: default
     config:
      - subnet: 10.0.2.0/24
